# Generated by Django 4.1.2 on 2023-06-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioRest', '0020_auto_20210429_0223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='resume/')),
                ('pdf', models.FileField(upload_to='resume/')),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='backend_category',
            field=models.CharField(blank=True, choices=[('Node.js', 'Node.js'), ('Uncategorized', 'Uncategorized'), ('Ruby', 'Ruby'), ('Flask', 'Flask'), ('Django', 'Django'), ('Python Application', 'Python Application')], default='Uncategorized', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='frontend_category',
            field=models.CharField(blank=True, choices=[('Angular.js', 'Angular.js'), ('Uncategorized', 'Uncategorized'), ('React.js', 'React.js'), ('Vue.js', 'Vue.js')], default='Uncategorized', max_length=100, null=True),
        ),
    ]
