# Generated by Django 4.1.2 on 2023-06-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioRest', '0023_generalinformation_slide1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinformation',
            name='slide1',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='slide2',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='slide3',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='slide4',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='slide5',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='backend_category',
            field=models.CharField(blank=True, choices=[('Django', 'Django'), ('Node.js', 'Node.js'), ('Ruby', 'Ruby'), ('Uncategorized', 'Uncategorized'), ('Python Application', 'Python Application'), ('Flask', 'Flask')], default='Uncategorized', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='frontend_category',
            field=models.CharField(blank=True, choices=[('Vue.js', 'Vue.js'), ('Uncategorized', 'Uncategorized'), ('Angular.js', 'Angular.js'), ('React.js', 'React.js')], default='Uncategorized', max_length=100, null=True),
        ),
    ]
