# Generated by Django 4.1.2 on 2023-06-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioRest', '0025_alter_generalinformation_slide1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalinformation',
            name='slide1',
        ),
        migrations.RemoveField(
            model_name='generalinformation',
            name='slide2',
        ),
        migrations.RemoveField(
            model_name='generalinformation',
            name='slide3',
        ),
        migrations.RemoveField(
            model_name='generalinformation',
            name='slide4',
        ),
        migrations.RemoveField(
            model_name='generalinformation',
            name='slide5',
        ),
        migrations.AlterField(
            model_name='project',
            name='backend_category',
            field=models.CharField(blank=True, choices=[('Node.js', 'Node.js'), ('Flask', 'Flask'), ('Uncategorized', 'Uncategorized'), ('Python Application', 'Python Application'), ('Ruby', 'Ruby'), ('Django', 'Django')], default='Uncategorized', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='frontend_category',
            field=models.CharField(blank=True, choices=[('Uncategorized', 'Uncategorized'), ('Vue.js', 'Vue.js'), ('React.js', 'React.js'), ('Angular.js', 'Angular.js')], default='Uncategorized', max_length=100, null=True),
        ),
    ]
