# Generated by Django 4.1.2 on 2023-06-09 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioRest', '0026_remove_generalinformation_slide1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalinformation',
            name='slide1',
            field=models.FileField(blank=True, upload_to='sliders/'),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='slide2',
            field=models.FileField(blank=True, upload_to='sliders/'),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='slide3',
            field=models.FileField(blank=True, upload_to='sliders/'),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='slide4',
            field=models.FileField(blank=True, upload_to='sliders/'),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='slide5',
            field=models.FileField(blank=True, upload_to='sliders/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='backend_category',
            field=models.CharField(blank=True, choices=[('Node.js', 'Node.js'), ('Django', 'Django'), ('Flask', 'Flask'), ('Uncategorized', 'Uncategorized'), ('Ruby', 'Ruby'), ('Python Application', 'Python Application')], default='Uncategorized', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='frontend_category',
            field=models.CharField(blank=True, choices=[('Angular.js', 'Angular.js'), ('Uncategorized', 'Uncategorized'), ('React.js', 'React.js'), ('Vue.js', 'Vue.js')], default='Uncategorized', max_length=100, null=True),
        ),
    ]
