# Generated by Django 4.1.2 on 2023-06-09 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioRest', '0027_generalinformation_slide1_generalinformation_slide2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='document',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='backend_category',
            field=models.CharField(blank=True, choices=[('Ruby', 'Ruby'), ('Flask', 'Flask'), ('Node.js', 'Node.js'), ('Python Application', 'Python Application'), ('Django', 'Django'), ('Uncategorized', 'Uncategorized')], default='Uncategorized', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='frontend_category',
            field=models.CharField(blank=True, choices=[('React.js', 'React.js'), ('Angular.js', 'Angular.js'), ('Vue.js', 'Vue.js'), ('Uncategorized', 'Uncategorized')], default='Uncategorized', max_length=100, null=True),
        ),
    ]
