# Generated by Django 4.1.2 on 2023-06-10 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioRest', '0028_project_document_alter_project_backend_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='backend_category',
            field=models.CharField(blank=True, choices=[('Uncategorized', 'Uncategorized'), ('Flask', 'Flask'), ('Ruby', 'Ruby'), ('Python Application', 'Python Application'), ('Node.js', 'Node.js'), ('Django', 'Django')], default='Uncategorized', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='frontend_category',
            field=models.CharField(blank=True, choices=[('Angular.js', 'Angular.js'), ('Uncategorized', 'Uncategorized'), ('Vue.js', 'Vue.js'), ('React.js', 'React.js')], default='Uncategorized', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('info', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='portfolioRest.generalinformation')),
            ],
        ),
    ]
